#连接Mirai的WS Url
connectUrl: ws://127.0.0.1:8081

#Mirai连接key
key: INITKEYVYTWM9qc

#Mirai连接qq
qq: 3544175039

#发消息群聊
group: 
  - 615056067

#有权限操作机器人的qq
admin:
  - 2351078777

#关闭服务器的命令
stopCmd: stop

#最低输出等级
LoggerLevel: debug

#控制台自动染色
ConsoleColor: true

#配置文件版本(勿动)
Version: 2